---
# ------------------------------------------------
# App-of-apps GitOps source
# ------------------------------------------------

# set to true to continue deployment even if child apps fail to sync/healthy
ocp4_workload_platform_engineering_workshop_wait_for_apps_ignore_errors: false

ocp4_workload_platform_engineering_workshop_gitops_repo: https://github.com/redhat-pe-workshop/ocp-pe-wkshp-helm-infra.git
ocp4_workload_platform_engineering_workshop_gitops_repo_tag: main

# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

# ------------------------------------------------
# OpenShift Pipelines
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_openshift_pipelines_namespace: openshift-operators

# ------------------------------------------------
# NooBaa
# ------------------------------------------------

# set to false when deploying on a cluster with ODF installed
ocp4_workload_platform_engineering_workshop_noobaa_install: true
ocp4_workload_platform_engineering_workshop_noobaa_namespace: openshift-storage
ocp4_workload_platform_engineering_workshop_noobaa_name: noobaa

# ------------------------------------------------
# GitLab
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_gitlab_namespace: gitlab
ocp4_workload_platform_engineering_workshop_gitlab_gitops_name: gitlab

ocp4_workload_platform_engineering_workshop_gitlab_config_smtp_host:
  smtp.gitlab-{{ ocp4_workload_platform_engineering_workshop_gitlab_namespace }}.{{ r_openshift_subdomain }}
ocp4_workload_platform_engineering_workshop_gitlab_config_ssh_host:
  ssh.gitlab-{{ ocp4_workload_platform_engineering_workshop_gitlab_namespace }}.{{ r_openshift_subdomain }}
ocp4_workload_platform_engineering_workshop_gitlab_config_root_password: "{{ common_password }}"
ocp4_workload_platform_engineering_workshop_gitlab_config_host:
  "gitlab-{{ ocp4_workload_platform_engineering_workshop_gitlab_namespace }}.{{ r_openshift_subdomain }}"

ocp4_workload_platform_engineering_workshop_gitlab_users_password: "{{ common_password }}"

# ------------------------------------------------
# Red Hat Build Of Keycloak
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_rhbk_client_backstage_name: backstage
ocp4_workload_platform_engineering_workshop_rhbk_application_name: keycloak
ocp4_workload_platform_engineering_workshop_rhbk_namespace: keycloak

ocp4_workload_platform_engineering_workshop_rhbk_cr_name: keycloak
ocp4_workload_platform_engineering_workshop_rhbk_external_access: false
ocp4_workload_platform_engineering_workshop_rhbk_host: sso

ocp4_workload_platform_engineering_workshop_rhbk_realm_backstage_name: backstage

ocp4_workload_platform_engineering_workshop_rhbk_client_backstage_secret:
  "{{ lookup('ansible.builtin.password', '/tmp/passwordfile-client-backstage', chars=['ascii_letters', 'digits'], length=32) }}"

ocp4_workload_platform_engineering_workshop_rhbk_client_backstage_plugin_name:
  "{{ ocp4_workload_platform_engineering_workshop_rhbk_realm_backstage_name }}-plugin"
ocp4_workload_platform_engineering_workshop_rhbk_client_backstage_plugin_secret:
  "{{ lookup('ansible.builtin.password', '/tmp/passwordfile-client-backstage-plugin', chars=['ascii_letters', 'digits'], length=32) }}"

ocp4_workload_platform_engineering_workshop_rhbk_user_password: "{{ common_password }}"

ocp4_workload_platform_engineering_workshop_rhbk_client_tpacli_secret:
  "{{ lookup('ansible.builtin.password', '/tmp/passwordfile-client-tpacli', chars=['ascii_letters', 'digits'], length=32) }}"



# ------------------------------------------------
# Quay
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_quay_application_name: quay
ocp4_workload_platform_engineering_workshop_quay_namespace: quay-registry

ocp4_workload_platform_engineering_workshop_quay_registry_host: "quay.{{ r_openshift_subdomain }}"
ocp4_workload_platform_engineering_workshop_quay_admin_user: quayadmin
ocp4_workload_platform_engineering_workshop_quay_admin_user_password: "{{ common_password }}"

ocp4_workload_platform_engineering_workshop_quay_organizations:
  - parasol
ocp4_workload_platform_engineering_workshop_quay_users:
  - username: dev1
    email: dev1@rhdh.com
    password: "{{ common_password }}"
  - username: dev2
    email: dev2@rhdh.com
    password: "{{ common_password }}"

# ------------------------------------------------
# LLM / LiteLLM
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_litellm_api_url: >-
  {{ lookup('agnosticd_user_data', 'litellm_api_base_url') | default('') }}
ocp4_workload_platform_engineering_workshop_litellm_api_key: >-
  {{ lookup('agnosticd_user_data', 'litellm_virtual_key') | default('') }}


# ------------------------------------------------
# Vault
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_vault_namespace: vault
ocp4_workload_platform_engineering_workshop_vault_name: vault
ocp4_workload_platform_engineering_workshop_vault_auth_namespace: default

# ------------------------------------------------
# External Secrets
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_external_secrets_namespace: external-secrets

# ------------------------------------------------
# RHDH GitOps
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_rhdh_gitops_namespace: rhdh-gitops
ocp4_workload_platform_engineering_workshop_rhdh_gitops_name: rhdh-gitops
ocp4_workload_platform_engineering_workshop_rhdh_gitops_password: "{{ common_password }}"

# ------------------------------------------------
# Red Hat Developer Hub
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_rhdh_argo_application_name: backstage-bootstrap
ocp4_workload_platform_engineering_workshop_rhdh_namespace: rhdh
ocp4_workload_platform_engineering_workshop_rhdh_psql_password: password

# ------------------------------------------------
# Developer Hub (Operator-based deployment)
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_developer_hub_namespace: rhdh
ocp4_workload_platform_engineering_workshop_developer_hub_config_git_host: github.com
ocp4_workload_platform_engineering_workshop_developer_hub_config_git_group: redhat-ads-tech
ocp4_workload_platform_engineering_workshop_developer_hub_config_git_repo: ocp-app-platform-demo-developer-hub-config
ocp4_workload_platform_engineering_workshop_developer_hub_config_git_revision: main

# ------------------------------------------------
# Orchestrator
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_orchestrator_application_name: orchestrator
ocp4_workload_platform_engineering_workshop_orchestrator_namespace: >-
  {{ ocp4_workload_platform_engineering_workshop_rhdh_namespace }}
ocp4_workload_platform_engineering_workshop_orchestrator_token: >-
  {{ lookup('ansible.builtin.password', '/tmp/passwordfile-orchestrator-token', chars=['ascii_letters', 'digits'], length=24) }}

# ------------------------------------------------
# OpenShift Dev Spaces
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_devspaces_install: true

ocp4_workload_platform_engineering_workshop_rhbk_client_openshift_name: openshift
ocp4_workload_platform_engineering_workshop_rhbk_client_openshift_secret:
  "{{ lookup('ansible.builtin.password', '/tmp/passwordfile-client-openshift', chars=['ascii_letters', 'digits'], length=32) }}"

ocp4_workload_platform_engineering_workshop_openshift_oauth_name: openshift-oauth
ocp4_workload_platform_engineering_workshop_openshift_oauth_namespace: openshift-config

# ------------------------------------------------
# Red Hat Trusted Artifact Signer
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_rhtas_application_name: trusted-artifact-signer
ocp4_workload_platform_engineering_workshop_rhtas_namespace: trusted-artifact-signer

ocp4_workload_platform_engineering_workshop_rhtas_instance_name: securesign
ocp4_workload_platform_engineering_workshop_rhtas_oidc_issuer:
  "{{ ocp4_workload_platform_engineering_workshop_rhbk_host }}.{{ r_openshift_subdomain }}/realms/{{ ocp4_workload_platform_engineering_workshop_rhbk_realm_backstage_name }}" # yamllint disable-line rule:line-length
ocp4_workload_platform_engineering_workshop_rhtas_root_cert_email: admin@rhdemo.com
ocp4_workload_platform_engineering_workshop_rhtas_root_cert_org: Parasol

# ------------------------------------------------
# Red Hat Trusted Profile Analyzer
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_tpa_application_name: trusted-profile-analyzer
ocp4_workload_platform_engineering_workshop_tpa_namespace: trusted-profile-analyzer
ocp4_workload_platform_engineering_workshop_tpa_s3_region: "https://s3-{{ ocp4_workload_platform_engineering_workshop_noobaa_namespace }}.{{ r_openshift_subdomain }}:443"
ocp4_workload_platform_engineering_workshop_tpa_appDomain: "-{{ ocp4_workload_platform_engineering_workshop_tpa_namespace }}.{{ r_openshift_subdomain }}"
ocp4_workload_platform_engineering_workshop_tpa_oidc_issuer:
  "https://{{ ocp4_workload_platform_engineering_workshop_rhbk_host }}.{{ r_openshift_subdomain }}/realms/{{ ocp4_workload_platform_engineering_workshop_rhbk_realm_backstage_name }}" # yamllint disable-line rule:line-length

# ------------------------------------------------
# Red Hat Advanced Cluster Security
# ------------------------------------------------

ocp4_workload_platform_engineering_workshop_acs_application_name: acs
ocp4_workload_platform_engineering_workshop_acs_namespace: stackrox 
ocp4_workload_platform_engineering_workshop_acs_clustername: local-cluster
ocp4_workload_platform_engineering_workshop_acs_adminpassword: "{{ common_password }}"
